import styles from './Home.module.scss';
import Head from 'next/head';
import Layout from '../components/Layout/Layout';
import HeroSection from '../components/HeroSection/HeroSection';
import MissionSection from '../components/MissionSection/MissionSection';
import BenefitsSection from '../components/BenefitsSection/BenefitsSection';
import DownloadBanner from '../components/DownloadBanner/DownloadBanner';
import FeaturesSection from '../components/FeaturesSection/FeaturesSection';
import TestimonialsSection from '../components/TestimonialsSection/TestimonialsSection';

const Home = () => {
  return (
    <Layout>
      <Head>
        <title>Gemma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <MissionSection />
      <BenefitsSection />
      <DownloadBanner />
      <FeaturesSection />
      <TestimonialsSection />
    </Layout>
  );
};

export default Home;
