import Head from 'next/head'
import Image from 'next/image'
import styles from './Home.module.scss'

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gemma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
TESTINg
      
    </div>
  )
}

export default Home;
