import styles from './Home.module.scss';
import Head from 'next/head';
import Layout from '../components/Layout/Layout';
import HeroSection from '../components/HeroSection/HeroSection';
import MissionSection from '../components/MissionSection/MissionSection';

const Home = () => {
  return (
    <Layout>
      <Head>
        <title>Gemma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <MissionSection />
    </Layout>
  );
};

export default Home;
